config/routes.rb
FacebookAuthExample::Application.routes.draw do
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    resources :sessions, only: [:create, :destroy]

    resource :home, only: [:default, :putImage]
    resources :home do
		collection do
		  get "dashboard"
		  get "facebookGroup"
		  get "create"
		  get "putCheckBox"
		  get "privacy"
		   get "myorder"
		  post "putImage"
	   end
	  end
	  
	   resources :orders do
		get :execute
		get :cancel
	  end

    root to: "home#default"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 

 
  def show
  end
  
  def dashboard
  		
  	@order = Order.new

	  if session["user_id"]
		graph = Koala::Facebook::GraphAPI.new(session["user_token"])
		@likes = graph.get_connections("me", "groups")
	   else
		redirect_to root_path
	   end
  end
  
   def create
   
   checkBoxVal=session["user_check_box"]
   
   checkBoxVal.each do |i|
	  	graph = Koala::Facebook::GraphAPI.new(session["user_token"])
		image_path="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpa1/v/t1.0-1/c0.0.50.50/p50x50/10423943_655616364534852_6986801926670704871_n.jpg?oh=3cb50271dddaeccb7ed9adc647d43c14&oe=545D7B35&__gda__=1416174859_39a1b78ba96d67b5ce0f12b17a5ed398"
		message = 'Ruby is the most beautiful gem.'
		graph.put_picture( image_path, {message: message}, i)
	end
	
   end
   
    def putCheckBox
	 session[:user_check_box] = params[:type]
	 session[:productName] = params[:productName]
	 session[:productDesc] = params[:productDesc]
	 session[:links] = params[:links]
	 session[:linkTitle] = params[:linkTitle]
	 session[:uploadFile] = params[:uploadFile]
	 render text: session["user_check_box"]
   end
   
 	def putImage
 		img = "#{params[:current_user]}_facebook_post.png"
 		File.open("public/#{img}", 'wb') do|f|
		f.write(Base64.decode64(params[:data]))
		end
		render text: "#{request.protocol}#{request.host_with_port}/#{img}"
 	end  
  
  def facebookGroup
	
  	#render text: "#{request.protocol}#{request.host_with_port}/#{session[:user_tbl_id]}_facebook_post.png"
	checkBoxVal = session["user_check_box"]
	graph = Koala::Facebook::GraphAPI.new(session[:user_token])
	checkBoxVal.each do |i|
		image_path="http://mintywhite.com/wp-content/uploads/2012/10/fond-ecran-wallpaper-image-arriere-plan-hd-29-HD.jpg"
		message = "#{session[:links]}
				  #{session[:productName]}
				  #{session[:productDesc]}"

		


		if(session[:uploadFile]!='')		
		#graph.put_picture( 'http://facebookeasylister.com/assets/logo-70f8cbc1d054d7f4276e1b29db24b31b.png', {message: 'test'}, i)
		else
		#graph.put_object(i, "feed", message: 'my test')	
		end	
	end

	graph = Koala::Facebook::GraphAPI.new(session["user_token"])
  		fbUser = graph.get_objects('me')
  		fbUserId = fbUser['me']['id'] #10152639308085731 
	render text: fbUser
	
	
  end
  
  def privacy
  
  end

   def myorder
  
   if session["user_id"]
		current_user= User.find(session["user_tbl_id"])
		@orders = current_user.orders.all( :limit => 100, :order => "id DESC" )

	else
		#redirect_to root_path
	end
	
  end
  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<script>
$(function(){
	$("#selectall").click(function(){
	$("input[type='checkbox']").prop("checked", true);
	setOrder();
	});
	
	$("#deselectall").click(function(){
	$("input[type='checkbox']").prop("checked", false);
	setOrder();
	});
	
	
	
	/*$("#addlink").click(function(){
		$("#linkinfo").toggle();
		$("#picupload").hide();
		});
		$("#addpic").click(function(){
			$("#picupload").toggle();
			$("#linkinfo").hide();
		})*/
});

function fillData() {
	var selected = new Array();
	var product_name =$("#product_name").val();
	var product_desc =$("#product_desc").val();
	var links =$("#link").val(); 
	var linkTitle =$("#linkTitle").val();


	   $("input[type=checkbox]:checked").each(function() {
       selected.push($(this).val());
		});
		
		if(selected.length==0)
		{
			alert("Please check atleast one group!");
			return false;
		}
		
		else if(product_name=="" || product_name==null) {
			alert("Please fill product name!");
			$("#product_name").focus();
			return false;
			
		}
		
		else if(product_desc=="" || product_desc==null) {
			alert("Please fill product description!");
			$("#product_desc").focus();
			return false;
			
		}

		$(".custom_btn").attr("href","/orders?order%5Bamount%5D=20&amp;order%5Bdescription%5D=Post");
		
}	

function setOrder()
{
	var selected = new Array();
	 $("input[type=checkbox]:checked").each(function() {
   selected.push($(this).val());
	});
	
	var product_name =$("#product_name").val();
	var product_desc =$("#product_desc").val();
	var links =$("#link").val(); 
	var linkTitle =$("#linkTitle").val();
	var uploadFile=$("#upload_file").val();

	var RegExp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
	if(!RegExp.test(links) &&  links!='')
	{
	links = 	"http://"+links;
	}


	$.ajax({
			url:"putCheckBox",
			data:{type:selected,productName:product_name,productDesc:product_desc,links:links,linkTitle:linkTitle,uploadFile:uploadFile},
			type:'GET',
			success:function(result){
				}
		
		});	
}

function readImage(input) {
    if ( input.files && input.files[0] ) {
        var FR= new FileReader();
        FR.onload = function(e) {
        uploadImage(e.target.result);
        };       
        FR.readAsDataURL( input.files[0] );
    }
}


function uploadImage(img)
{
$("#img_loading").show();
$("#post_btn").attr('disabled',true);
$data = img.split(',');	
$.ajax({
	url:"putImage",
	data:{data: $data[1],current_user: $("#current_user").val()},
	type:'POST',
	success:function(result){
	setOrder();	
	$("#img_loading").hide();	
	$("#post_btn").attr('disabled',false);
		}

});	
}


$(function(){
$("#upload_file").change(function(){
$img = readImage( this );
});


});	
	
</script>

<input type="hidden" id="current_user" value="<%=session[:user_tbl_id]%>"/>

<div class="page-wrap">
<section class="inner_heading_part">
      
     <h2>Post to Multiple (Groups)</h2>
     
</section>
<div class="container"> 
		
		<div class="row">
			<div class="col-sm-6 col-xs-12">
				
				
				<form class="form-horizontal upload-post"  action="putCheckBox" method="post" > 
				
				<div class="form-group">				
					<label for="inputEmail3" class="col-sm-4 control-label">Product Name</label>					
					<div class="col-sm-8">
						<!-- <input type="text" class="form-control" id="exampleInputPassword1"> -->
						 <textarea class="form-control" rows="3" name="product_name" id="product_name" required onBlur="setOrder()"></textarea>
					</div>
				  </div>
				  <div class="form-group">
					<label for="inputEmail3" class="col-sm-4 control-label">Product Description<br/></label>
					<div class="col-sm-8">
					 <textarea class="form-control" rows="3" name="product_desc" id="product_desc" required onBlur="setOrder()"></textarea>
					</div>
				  </div>
				 <!-- <div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
						<i class="fa fa-plus-circle"></i><a href="#" id="addlink"> Add link |</a>
						<a href="#" id="addpic"> Add image</a>
					</div>
				  </div> -->
				  
				  
				  <div  id="linkinfo" >
					  <div class="form-group" >
							<label class="col-sm-4 control-label">Link</label>
							<div class="col-sm-8">
							 <input type="text" class="form-control" id="link" name="link" value="" onBlur="setOrder()" />
							 
							</div>
				     </div>	
				     
				     <!-- <div class="form-group">		
							<label class="col-sm-4 control-label">Sub Title </label>
							<div class="col-sm-8">
							 <input type="text" class="form-control" name="linkTitle" id="linkTitle" onBlur="setOrder()" />
							 </div>
				       </div> -->
				     
				     
				    </div> 
				   
				     <div class="form-group">	<label class="col-sm-4 control-label">Choose Image</label>  			 
						<div class="col-sm-4"></div>	 
							<div class="col-sm-8">
								<div id="picupload" class="upload-picture" style="display:block;">
									<input name="file" id="upload_file" class="form-control" type="file"/>
									<span id="img_loading" style="float: left; font-weight: bold; color: rgb(44, 44, 44); padding: 6px 0px 0px;display:none;"> loading...</span>
								</div>
							</div>
						</div>	
					
					 <div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
						<!--
					  <button type="submit" class="btn btn-success" >Post</button> -->
					  
					  
					  <a rel="nofollow" id="post_btn" onclick="return fillData()" data-method="post" class="btn  custom_btn post_btn" href="javascript:;">Post</a>
					</div>
				  </div>
				  </div>
				  
				  
			
				
			
			<div class="col-sm-6 col-xs-12">
				
					<div class="form-group">
						<div class="col-sm-12">
							<h4>Select Groups to Post to:</h4>
							<div class="pull-right right_section">
								<a href="javascript:void(0)" id="selectall">Select all -</a>
								<a href="javascript:void(0)" id="deselectall">Deselect all</a>
								<br/>
								
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<div class="mang_width">
								<div id="ugroups">
									<% if @likes %>
										<% for like in @likes %>
									
									<div class="gdiv">
										<input type="checkbox" id="<%=h like["id"]%>" name="usergroups[<%=h like["id"]%>]" value="<%=h like["id"]%>" onClick="setOrder()" /> 
										<label for="<%=h like["id"]%>">
											<span class="gname"><%=h like["name"]%></span>
										</label>
									</div>
									
									<% end %>
									<% end %>
											
								</div>
							</div>
						</div>
					</div>	
					
					</form>			
				
			</div>
		</div>
    </div> <!-- /container -->
</div>
    </div> <!-- /container -->

app/views/home/default.html.erb
   <div class="main_page">
  		<div class="heading_part">
  			<div class="container">
				<div class="row">
					<div class="col-sm-12 col-xs-12">
						<h2>
							Post to Multiple (Groups)<br/>
							<small>The one and only Facebook Multiple Groups Poster Tool </small>
						</h2>
					</div>
				</div>
			</div>
		</div>
		</div>

        <div class="container"> 
			<div class="row">
				<div class="col-sm-7 col-xs-12">
					<div class="feature">
					<h3>Features</h3>
					<ul>
						<li>
							<a href="#">
								<%= image_tag("check.1.png") %>
								Bulk post to Facebook groups you have joined
							</a>
						</li>
						<li>
							<a href="#">
								<%= image_tag("check.1.png") %>
								Bulk Posting "Image Comments" (when using commentator mode)
							</a>
						</li>
						<li>
							<a href="#">
								<%= image_tag("check.1.png") %>
								Fast, simple and easy to use
							</a>
						</li>
						<!-- <li>
							<a href="#">
								<i class="fa fa-check">&nbsp;</i>
								and many more...
							</a>
						</li> -->
					</ul>
				</div>			
			</div>

			<div class="col-sm-5 col-xs-12 cont_center login-with-fb ">
					
				<h3>Login with Facebook and start posting now !</h3>
				<%= link_to( image_tag("login-with-facebook.jpeg"), "/auth/facebook" ) %>
			</div>
		</div>
		
		</div>

    







   

app/views/home/facebookGroup.erb
<table border="0">
<% if @likes %>
<% for like in @likes %>
<tr>
<td><b><%=h like["name"]%> </b></td>
</tr>
<tr>
<td><%=h like["category"] %></td>
</tr>
<tr>
<td>&ndash;</td>
</tr>
<% end %>
<% end %>
</table>

app/views/home/index.html.erb
%h2 Orders

%table.table
  %thead
    %tr
      %th Payment ID
      %th Amount($)
      %th Payment Status
      %th Time
      %th Description
      %th
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.payment_id
        %td= order.amount
        %td= order.state
        %td= order.created_at
        %td= order.description
        %td= link_to "Details", order_path(order)

app/views/home/myorder.html.erb
<div class='container' id='content'>
	  <div class="row">
	    <h1>Orders</h1>
	    
	  
      <div class="col-md-12">
      
   
      <table class='table table-bordered table-hover'>
      
       <tr>
       <td>Payment ID</td><td>Amount($)</td><td>Payment Status</td><td>Time</td><td>Product Name</td>
       </tr>

       <% @orders.each do |o|  %> 
       <tr>
       <td><%= o.payment_id  %></td><td>$<%= o.amount  %></td><td><%= o.state  %></td><td><%= o.created_at  %></td><td><%= o.description  %></td>
       </tr>

      <% end %>   
      </table>
    </div>    
    
		 <div class="clearfix"></div><br/><br/>
    
    </div>   
    </div>
        
        
 

app/views/home/show.html.erb
%h2 Order

%p
  %label Amount
  = @order.amount
%p
  %label Description
  = @order.description

%p
  %label Payment
  - if @order.payment.present?
    - if @order.payment.state == "approved"
      Payed with
      = @order.payment.payer.payment_method
    - elsif @order.approve_url
      = link_to "Pay with PayPal", @order.approve_url
    - else
      Payment or completed(#{@order.payment.state})